### ISSUE TITLE
Revisiting splitting of `expo` & `expo_plural_forms`

### ISSUE THREAD

**Issue by maennchen** [elixir-gettext/expo_plural_forms#37]
We split out `expo_plural_forms` for a few reasons:

* Dependencies - it needed `nimple_parsec`, that dependency is now gone
* Size - The size shrank with the work @whatyouhide put in and I think it is no longer an issue (+ 66K / 29.7%)

```console
$ du -h _build/dev/lib/expo/ebin # without plural forms
222K	_build/dev/lib/expo/ebin

$ du -h _build/dev/lib/expo/ebin # with plural forms
288K	_build/dev/lib/expo/ebin
```

* Compile Time - The compile time is a lot faster now as well (+ 0.18s / 11.3%)

```console
$ time mix compile --force # without plural forms
mix compile --force  2.40s user 0.20s system 244% cpu 1.063 total

$ time mix compile --force # with plural forms
mix compile --force  2.58s user 0.25s system 271% cpu 1.044 total
```

**Comment by whatyouhide** [comment]
So are you proposing that we put expo_plural_forms back into Expo?

I was under the impression that expo_plural_form could be used as an optional dependency by folks that use Gettext and want this behaviour. Other folks might be okay with other Gettext backends and avoid the dependency completely. Had I gotten it wrong?

**Comment by maennchen** [comment]
@whatyouhide Yes, that's what I'm proposing.

My idea of `expo` was a library that supports as much of the gettext standard (no runtime, just parsing etc.) as possible.

For me those two libraries go together logically even if `gettext` would potentially not use all features of it. (Which it already doesn't like for example `.mo`)

I see this the same as `plug` supporting uploads even if the consuming application does not.

When we decided to split, there was a massive size & compilation time difference and it made sense to split it. With the current state, I no longer think that is true.

I think merging them back together would also make maintenance slightly easier since there's one less git repo, set of GitHub workflows, hex publishing etc.

**Comment by whatyouhide** [comment]
Ah, okay, I see. Yes, agreed then. Let's merge it back together. Let me take care of it then @maennchen 💟

**Comment by maennchen** [comment]
@whatyouhide Can we do it this way?

```diff
diff --git a/README.md b/README.md
index 184e278..72bf275 100644
--- a/README.md
+++ b/README.md
@@ -1,38 +1,4 @@
 # Expo Plural Forms
 
-[![hex.pm badge](https://img.shields.io/badge/Package%20on%20hex.pm-informational)](https://hex.pm/packages/expo_plural_forms)
-[![Documentation badge](https://img.shields.io/badge/Documentation-ff69b4)][docs]
-[![.github/workflows/branch_main.yml](https://github.com/elixir-gettext/expo_plural_forms/actions/workflows/branch_main.yml/badge.svg)](https://github.com/elixir-gettext/expo_plural_forms/actions/workflows/branch_main.yml)
-[![Coverage Status](https://coveralls.io/repos/github/elixir-gettext/expo_plural_forms/badge.svg?branch=main)](https://coveralls.io/github/elixir-gettext/expo_plural_forms?branch=main)
-
-> A parser for plural form headers in PO files.
-
-This small library supports parsing `Plural-Form` headers in PO or POT files,
-which are the files used by [GNU Gettext][gnu-gettext]. There is [documentation
-for the `Plural-Form`
-header](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html)
-in the Gettext documentation.
-
-In the near future, we will use this library in the [Gettext bindings for
-Elixir][gettext].
-
-## Usage
-
-Documentation can be found [on Hexdocs][docs].
-
-This library ships with a built-in list of languages and their plural forms. You
-can find which plural form to use for a given *amount* by using
-`ExpoPluralForms.index/2`:
-
-```elixir
-{:ok, plural_form} = ExpoPluralForms.plural_form("de")
-
-ExpoPluralForms.index(plural_form, 1)
-#=> 0
-ExpoPluralForms.index(plural_form, 213)
-#=> 1
-```
-
-[docs]: https://hexdocs.pm/expo_plural_forms
-[gnu-gettext]: https://www.gnu.org/software/gettext/
-[gettext]: https://github.com/elixir-gettext/gettext
+Integrated into [`expo`](https://github.com/elixir-gettext/expo).
+See https://github.com/elixir-gettext/expo/pull/102
```

And then set it to archived in the settings?
